/**
 * Turns flat model outputs into a predictable ZIP tree + SETUP.md instructions.
 */

export type BundleFile = { path: string; content: string };

export type BundleLayoutSummary = {
  terraformCount: number;
  supplementalCount: number;
  hasDocker: boolean;
  hasHelm: boolean;
  hasGithubActions: boolean;
  hasKubernetesDir: boolean;
  deliveryExtras: number;
};

function basename(p: string): string {
  const parts = p.replace(/\\/g, "/").split("/");
  return parts[parts.length - 1] || p;
}

function isDockerRelatedPath(rel: string): boolean {
  const b = basename(rel).toLowerCase();
  const lower = rel.toLowerCase();
  if (b === "dockerfile" || b.startsWith("dockerfile.")) return true;
  if (b === ".dockerignore") return true;
  if (b.startsWith("docker-compose") && (b.endsWith(".yml") || b.endsWith(".yaml")))
    return true;
  if (lower.includes("containerfile")) return true;
  return false;
}

function normalizeInnerPath(path: string): string {
  return path.replace(/^\/+/, "").replace(/\.\./g, "").replace(/\\/g, "/");
}

/**
 * Maps supplemental paths into docker/, delivery/, or preserves helm / .github / k8s roots.
 */
export function targetPathForSupplemental(rel: string): string {
  const p = normalizeInnerPath(rel);
  if (!p) return "delivery/unnamed.txt";

  if (
    p.startsWith(".github/") ||
    p.startsWith("helm/") ||
    p.startsWith("charts/") ||
    p.startsWith("kubernetes/") ||
    p.startsWith("k8s/")
  ) {
    return p;
  }

  if (isDockerRelatedPath(p)) {
    return `docker/${basename(p)}`;
  }

  if (p.startsWith("scripts/") || p.startsWith("script/")) {
    return `delivery/${p}`;
  }

  const b = basename(p);
  if (b === "Makefile" || b.endsWith(".mk")) {
    return `delivery/${p.includes("/") ? p : b}`;
  }

  if (
    p === ".gitlab-ci.yml" ||
    p === "azure-pipelines.yml" ||
    p.endsWith(".gitlab-ci.yml")
  ) {
    return `delivery/ci/${basename(p)}`;
  }

  if (p.includes("/")) {
    return `delivery/${p}`;
  }

  return `delivery/${p}`;
}

/**
 * All Terraform-related files live under terraform/
 */
export function targetPathForTerraform(rel: string): string {
  const p = normalizeInnerPath(rel);
  if (!p) return "terraform/generated.tf";
  return `terraform/${p}`;
}

export function summarizeBundle(
  terraform: BundleFile[],
  supplemental: BundleFile[],
  finalPaths: string[],
): BundleLayoutSummary {
  const hasDocker = finalPaths.some((p) => p.startsWith("docker/"));
  const hasHelm = finalPaths.some(
    (p) => p.startsWith("helm/") || p.startsWith("charts/"),
  );
  const hasGithubActions = finalPaths.some((p) =>
    p.startsWith(".github/workflows/"),
  );
  const hasKubernetesDir = finalPaths.some(
    (p) => p.startsWith("kubernetes/") || p.startsWith("k8s/"),
  );
  const deliveryExtras = finalPaths.filter((p) => p.startsWith("delivery/"))
    .length;

  return {
    terraformCount: terraform.length,
    supplementalCount: supplemental.length,
    hasDocker,
    hasHelm,
    hasGithubActions,
    hasKubernetesDir,
    deliveryExtras,
  };
}

export function generateSetupMarkdown(summary: BundleLayoutSummary): string {
  const lines: string[] = [
    "# NLP → Infra — Step-by-step setup",
    "",
    "This archive was generated by **NLP → Infra**. Treat every file as a **starting point**: review security, costs, and naming before production.",
    "",
    "## 1. What is in this ZIP",
    "",
    "| Path | Purpose |",
    "|------|---------|",
    "| `SETUP.md` | This guide |",
    "| `terraform/` | Infrastructure as code (`*.tf`, tfvars example, Terraform README) |",
  ];

  if (summary.hasDocker) {
    lines.push("| `docker/` | `Dockerfile`, compose files, `.dockerignore` |");
  }
  if (summary.hasHelm) {
    lines.push("| `helm/` or `charts/` | Kubernetes Helm chart(s) |");
  }
  if (summary.hasGithubActions) {
    lines.push(
      "| `.github/workflows/` | GitHub Actions (build / deploy). **Copy this tree to your app repo root** so GitHub discovers workflows. |",
    );
  }
  if (summary.hasKubernetesDir) {
    lines.push("| `kubernetes/` or `k8s/` | Raw manifests (if generated) |");
  }
  if (summary.deliveryExtras > 0) {
    lines.push(
      "| `delivery/` | Other assets (extra CI files, scripts, notes). Move or merge into your real repository as needed. |",
    );
  }

  lines.push(
    "",
    "## 2. Terraform (in order)",
    "",
    "1. Open a terminal and go to the Terraform folder:",
    "   ```bash",
    "   cd terraform",
    "   ```",
    "2. Copy the example variables file and edit values (VPC, subnets, region, ECR image URIs, secrets):",
    "   ```bash",
    "   cp terraform.tfvars.example terraform.tfvars   # if that example file exists",
    "   ```",
    "3. Install Terraform CLI (≥ 1.5) and initialize:",
    "   ```bash",
    "   terraform init",
    "   ```",
    "4. Review the execution plan:",
    "   ```bash",
    "   terraform plan",
    "   ```",
    "5. Apply only when the plan matches what you expect (creates/changes real cloud resources):",
    "   ```bash",
    "   terraform apply",
    "   ```",
    "",
    "**Notes:** Use a remote backend (S3 + DynamoDB, Terraform Cloud, etc.) for team workflows. Never commit real secrets in `terraform.tfvars`—use env vars, Vault, or your cloud secret manager.",
    "",
  );

  if (summary.hasDocker) {
    lines.push(
      "## 3. Docker images",
      "",
      "1. From the repo root (or `docker/` if you only have files there), build a test image:",
      "   ```bash",
      "   docker build -f docker/Dockerfile -t myapp:local .",
      "   ```",
      "   Adjust `-f` and build context if your `Dockerfile` expects files from a parent directory.",
      "2. Push to the registry referenced in Terraform (e.g. Amazon ECR) and use that URI in `terraform.tfvars` or task definitions.",
      "",
    );
  }

  if (summary.hasHelm) {
    lines.push(
      "## 4. Helm (Kubernetes)",
      "",
      "1. Install Helm 3 and `kubectl` configured for your cluster.",
      "2. Inspect the chart:",
      "   ```bash",
      "   helm lint ./helm/*",
      "   ```",
      "3. Dry-run an install with your values:",
      "   ```bash",
      "   helm upgrade --install myrelease ./helm/YOUR_CHART -f ./helm/YOUR_CHART/values.yaml --dry-run",
      "   ```",
      "4. Apply for real after you trust the manifest.",
      "",
    );
  }

  if (summary.hasGithubActions) {
    lines.push(
      "## 5. GitHub Actions",
      "",
      "1. Copy the `.github` folder into the **root** of the GitHub repository you want to build/deploy.",
      "2. In GitHub: **Settings → Secrets and variables → Actions** — add secrets referenced in the workflows (e.g. `AWS_ROLE_TO_ASSUME`, `AWS_REGION`, registry tokens).",
      "3. Ensure OIDC or access keys match what the YAML expects.",
      "4. Push to the branch configured in `on:` (often `main`) to trigger a run.",
      "",
    );
  }

  lines.push(
    "## 6. Delivery / other files",
    "",
    "Files under `delivery/` (and some CI filenames) may need to be **moved to the root** of your application repository (e.g. `.gitlab-ci.yml`, `Makefile`) depending on your platform.",
    "",
    "---",
    "",
    `*Bundle: ${summary.terraformCount} Terraform file(s), ${summary.supplementalCount} supplemental file(s).*`,
  );

  return lines.join("\n");
}

/**
 * Merge terraform + supplemental into a structured tree. Later duplicates overwrite earlier.
 */
export function buildStructuredBundle(
  terraform: BundleFile[],
  supplemental: BundleFile[],
): BundleFile[] {
  const map = new Map<string, string>();

  for (const f of terraform) {
    map.set(targetPathForTerraform(f.path), f.content);
  }

  for (const f of supplemental) {
    map.set(targetPathForSupplemental(f.path), f.content);
  }

  const paths = [...map.keys()].sort();
  const summary = summarizeBundle(terraform, supplemental, paths);
  const setup = generateSetupMarkdown(summary);

  map.set("SETUP.md", setup);

  return [...map.entries()].map(([path, content]) => ({ path, content }));
}
